name: Deploy to Vercel

env:
    SERVICE_NAME: resume-anonymizer

on:
    push:
        branches:
            - "v*.*.*"
    pull_request:
        branches:
            - "v*.*.*"

jobs:
    vercel-deploy:
        runs-on: ubuntu-latest

        env:
            TAG: ${{ github.ref_name }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

        steps:
          - uses: actions/checkout@v2
          - name: Install Vercel CLI
            run: npm install --global vercel@latest
          - name: Pull Vercel Environment Information
            run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
          - name: Create .env file
            run: |
                touch .env
                echo -n "${{secrets.ENV_SECRETS}}" | base64 -d >> .env
          - name: Build Project Artifacts
            run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
          - name: Deploy Project Artifacts to Vercel
            run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
